version: 0.1
os: linux
# files:
#   - source: Config/config.txt
#     destination: /webapps/Config
#   - source: source
#     destination: /webapps/myApp
hooks:
  BeforeInstall:
    - location: Scripts/DockerStop.sh
  AfterInstall:
    - echo "After install command"
    - location: Scripts/DockerStart.sh
      timeout: 180
  # ApplicationStart:
  #   - location: Scripts/RunFunctionalTests.sh
  #     timeout: 3600
  # ValidateService:
  #   - location: Scripts/MonitorService.sh
  #     timeout: 3600
  #     runas: codedeployuser
